### Добавление площадки

POST http://localhost:8080/api/places
Content-Type: application/json

{
  "title": "Площадка_1",
  "address": "Адрес_1"
}

### Добавление площадки

POST http://localhost:8080/api/places
Content-Type: application/json

{
  "title": "Площадка_2",
  "address": "Адрес_2"
}

### Получение площадок

GET http://localhost:8080/api/places

### Получение одной площадки

GET http://localhost:8080/api/places/1

### Добавление события на  площадку

POST localhost:8080/api/places/1/events
Content-Type: application/json

{
  "title": "Событие_1",
  "startDate": "2023-02-02",
  "expirationDate": "2023-02-03",
  "state": "COMPLETED"
}

### Добавление Добавление события на  площадку

POST localhost:8080/api/places/1/events
Content-Type: application/json

{
"title": "Событие_2",
"startDate": "2023-03-02",
"expirationDate": "2023-03-04",
"state": "STARTED"
}

### Добавление Добавление события на  площадку

POST localhost:8080/api/places/2/events
Content-Type: application/json

{
  "title": "Событие_3",
  "startDate": "2023-03-02",
  "expirationDate": "2023-03-04",
  "state": "STARTED"
}

### Получение всех событий на  площадке

GET http://localhost:8080/api/places/1/events
